### ISSUE TITLE
Exception when trying to browse/query data

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1277]
@bogo777 , try that, if you know how to solve that quickly, please solve that. If not, reassign please on @skodape 

To reproduce: 
- ODCS, exec monitor, exec 895
- click on browse/query
- select xslt, rdfInput
- click browse

An error occurs: 
2014-02-28 13:24:17,051 [http-bio-8080-exec-290] ERROR cz.cuni.mff.xrg.odcs.frontend.AppEntry - Uncaught exception
java.lang.NullPointerException: null
    at cz.cuni.mff.xrg.odcs.frontend.auxiliaries.RDFDataUnitHelper.getRepository(RDFDataUnitHelper.java:53) ~[RDFDataUnitHelper.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.container.rdf.RDFQuery.<init>(RDFQuery.java:57) ~[RDFQuery.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.container.rdf.RDFQueryFactory.constructQuery(RDFQueryFactory.java:25) ~[RDFQueryFactory.class:na]
    at org.vaadin.addons.lazyquerycontainer.LazyQueryView.getQuery(LazyQueryView.java:406) ~[vaadin-lazyquerycontainer-2.0.9.jar:2.0.9]
    at org.vaadin.addons.lazyquerycontainer.LazyQueryView.getQuerySize(LazyQueryView.java:392) ~[vaadin-lazyquerycontainer-2.0.9.jar:2.0.9]
    at org.vaadin.addons.lazyquerycontainer.LazyQueryView.size(LazyQueryView.java:219) ~[vaadin-lazyquerycontainer-2.0.9.jar:2.0.9]
    at org.vaadin.addons.lazyquerycontainer.LazyQueryContainer.size(LazyQueryContainer.java:183) ~[vaadin-lazyquerycontainer-2.0.9.jar:2.0.9]
    at cz.cuni.mff.xrg.odcs.frontend.gui.components.RDFQueryView.runQuery(RDFQueryView.java:369) ~[RDFQueryView.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.components.RDFQueryView.access$000(RDFQueryView.java:57) ~[RDFQueryView.class:na]
    at cz.cuni.mff.xrg.odcs.frontend.gui.components.RDFQueryView$1.buttonClick(RDFQueryView.java:106) ~[RDFQueryView$1.class:na]
    at sun.reflect.GeneratedMethodAccessor119.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:167) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:969) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.ui.Button.fireClick(Button.java:368) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.ui.Button$1.click(Button.java:57) ~[vaadin-server-7.1.8.jar:7.1.8]
    at sun.reflect.GeneratedMethodAccessor135.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:168) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118) ~[vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:207) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:91) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:37) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1371) [vaadin-server-7.1.8.jar:7.1.8]
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:238) [vaadin-server-7.1.8.jar:7.1.8]
    at cz.cuni.mff.xrg.odcs.frontend.ODCSApplicationServlet.service(ODCSApplicationServlet.java:74) [ODCSApplicationServlet.class:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) [servlet-api.jar:na]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [catalina.jar:7.0.33]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [catalina.jar:7.0.33]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.33]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) [catalina.jar:7.0.33]
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:931) [catalina.jar:7.0.33]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.33]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407) [catalina.jar:7.0.33]
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004) [tomcat-coyote.jar:7.0.33]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) [tomcat-coyote.jar:7.0.33]
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312) [tomcat-coyote.jar:7.0.33]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_40]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_40]
    at java.lang.Thread.run(Thread.java:724) [na:1.7.0_40]

**Comment by bogo777** [comment]
Do you have version after commit 3870b32131caf35fdc9e54a6446f546e6eb0e01d ? It should be fixed by it.

**Comment by tomas-knap** [comment]
Ok, will check on that

**Comment by tomas-knap** [comment]
Still appears, please check ODCS

**Comment by tomas-knap** [comment]
This problem still appears, see ODCS, exec 934, browse/query for XSLT/rdfInput.

![screen shot 2014-03-03 at 10 00 21 am](https://f.cloud.github.com/assets/3014917/2307814/734e1e54-a2b2-11e3-805f-374b99e35fed.png)

Please look on that

**Comment by bogo777** [comment]
I wasn't able to reproduce it on exec 934, but it occured for some RUIAN execution for me. It seems that this call:
executionInfo.dpu(dpuInstance)
returns null and is cause of the trouble. I added check, that it is so, so after loading newest version to odcs we could confirm it from log. But I will need help from @skodape , as I don't know why this code would return null for finished execution...

**Comment by tomas-knap** [comment]
@skoda, please look on that when you find some time

**Comment by tomas-knap** [comment]
Cannot reproduce
